// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA74tSxRuz9hzDK1ckwXu2uGTXZAjBR-ws',
    appId: '1:265781847133:android:90215b129cc63f8dc2d9b4',
    messagingSenderId: '265781847133',
    projectId: 'wave-414416',
    storageBucket: 'wave-414416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7kZ2pLrY612TnBmMy3sKOdhktJCFFO80',
    appId: '1:265781847133:ios:0429d40b027ae311c2d9b4',
    messagingSenderId: '265781847133',
    projectId: 'wave-414416',
    storageBucket: 'wave-414416.appspot.com',
    androidClientId: '265781847133-nsdtmjka0vf7933b45e2sb8m9o9kr8it.apps.googleusercontent.com',
    iosClientId: '265781847133-dr3epabha3cmj97u8q2kv97k7vp5uq15.apps.googleusercontent.com',
    iosBundleId: 'com.team.wave',
  );
}
